let shopItemsData = [
    {
      id: "TataTeaGoldTea",
      name: "Tata Tea Gold Tea",
      price: 45,
      img: "images/tea/Tata_Tea_Gold_Tea.avif",
    },
    {
      id: "BRUInstantCoffee",
      name: "BRU Instant Coffee (50 g)",
      price: 260,
      img: "images/tea/BRU_Instant_Coffee.avif",
    },
    {
      id: "LiptonHoneyLemonGreenTeaBags",
      name: "Lipton Honey Lemon Green Tea Bags",
      price: 150,
      img: "images/tea/Lipton_Honey_Lemon_Green_Tea_Bags.avif",
    },
    {
      id: "NescafeClassicInstantCoffee",
      name: "Nescafe Classic Instant Coffee",
      price: 170,
      img: "images/tea/Nescafe_Classic_Instant_Coffee.avif",
    },
    {
      id: "PediaSureVanillaDelightHealthDrinkPackof",
      name: "PediaSure Vanilla Delight Health Drink Pack of 2",
      price: 150,
      img: "images/tea/PediaSure_Vanilla_Delight_Health_Drink.avif",
    },
    {
      id: "HorlicksChocolateDelightHealthDrink",
      name: "Horlicks Chocolate Delight Health Drink",
      price: 250,
      img: "images/tea/Horlicks_Chocolate_Delight_Health_Drink.avif",
    },
    {
      id: "ComplanRoyaleChocolateNutritionandHealthDrink",
      name: "Complan Royale Chocolate Nutrition and Health Drink",
      price: 490,
      img: "images/tea/Complan-Royale-Chocolate-Nutrition-and-Health-Drink.avif",
    },
    {
      id: "HorlicksWomensPlusCaramelHealthDrink",
      name: "Horlicks Women's Plus Caramel Health Drink (Jar)",
      price: 320,
      img: "images/tea/Horlicks-Women's-Plus-Caramel-Health-Drink-(Jar).avif",
    },
    {
      id: "CadburyBournvitaChocolateHealthDrink",
      name: "Cadbury Bournvita Chocolate Health Drink",
      price: 370,
      img: "images/tea/Cadbury-Bournvita_Chocolate_Health_Drink.avif",
    },
    {
      id: "RawPresseryAloeVeraLemonadeDrink",
      name: "Raw Pressery Aloe Vera Lemonade Drink",
      price: 400,
      img: "images/tea/Raw_Pressery_Aloe_Vera_Lemonade_Drink.webp",
    },

    {
      id: "SunfeastStrawberryMilkshake",
      name: "Sunfeast Strawberry Milkshake",
      price: 37,
      img: "images/tea/Sunfeast_Strawberry_Milkshake.avif",
    },
    {
      id: "SunfeastDarkFantasyMilkshakewithBelgianChocolate",
      name: "Sunfeast Dark Fantasy Milkshake with Belgian Chocolate",
      price: 35,
      img: "images/tea/Sunfeast_Dark_Fantasy_Milkshake_with_Belgian_Chocolate.avif",
    },
    {
      id: "AmulLassi",
      name: "Amul Lassi",
      price: 17,
      img: "images/tea/Amul_Lassi.avif",
    },
    {
      id: "StingEnergyDrink",
      name: "Sting Energy Drink",
      price: 20,
      img: "images/tea/Sting_Energy_Drink.webp",
    },
    {
      id: "MonsterEnergyDrink",
      name: "Monster Energy Drink",
      price: 110,
      img: "images/tea/Monster-Energy-Drink.webp",
    },
    {
      id: "Nescafe_Intense_Cappuccino_Cold_Coffee",
      name: "Nescafe Intense Cappuccino Cold Coffee Pack of 2",
      price: 130,
      img: "images/tea/Nescafe_Intense_Cappuccino_Cold-Coffee.avif",
    },
    {
      id: "RedBullEnergyDrink",
      name: "Red Bull Energy Drink",
      price: 120,
      img: "images/tea/redbull.webp",
    },
    {
      id: "YakultProbioticHealthDrink",
      name: "Yakult Probiotic Health Drink",
      price: 150,
      img: "images/tea/Yakult_Probiotic_Health_Drink.avif",
    },
];